export type AppConfig = {
  local_device_id: string;
  local_device_name: string;
  shortcut: string;
  clipboard_window_width: number;
  clipboard_window_height: number;
  clipboard_window_spacing: number;
  share_files_view_mode: string;
  share_files_item_zoom: number;
  auto_cleanup_invalid_clipboard_data: boolean;
  cache_dir: string;
  remote_cache_dir: string;
  cleanup_after_days: number | null;
  max_items: number | null;
  default_share_text: boolean;
  default_share_image: boolean;
  default_share_file: boolean;
  default_share_folder: boolean;
  unshare_on_clipboard_change: boolean;
  auto_start_share_server: boolean;
  share_server_bind_ip: string;
  share_server_port: number;
  share_server_password_enabled: boolean;
  share_server_password_hash: string | null;
  share_server_auth_mode: number;
  browser_access_enabled: boolean;
  web_access_auth_required: boolean;
  web_access_password_enabled: boolean;
  web_access_password: string | null;
  web_access_temp_approval_enabled: boolean;
  web_access_cookie_ttl_seconds: number;
  web_access_scope_files: boolean;
  web_access_scope_clipboard_list: boolean;
  web_access_scope_clipboard_content: boolean;
  web_access_scope_download: boolean;
  sync_access_enabled: boolean;
  popup_on_inbound_request: boolean;
};

export type AppConfigUpdate = Partial<AppConfig> & {
  cleanup_after_days?: number | null;
  max_items?: number | null;
};
