//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "clipboard_record")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub r#type: i32,
    #[sea_orm(column_type = "Binary(1)", nullable)]
    pub data: Option<Vec<u8>>,
    #[sea_orm(column_type = "Text", nullable)]
    pub preview: Option<String>,
    #[sea_orm(unique)]
    pub hash: Option<String>,
    pub size: Option<i64>,
    pub source_app: Option<String>,
    pub created_at: i64,
    pub last_accessed_at: i64,
    pub access_count: i32,
    pub is_favorite: i32,
    pub is_shared: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
