//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "clipboard_record")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub r#type: String,
    #[sea_orm(column_type = "Binary(1)", nullable)]
    pub data: Option<Vec<u8>>,
    #[sea_orm(column_type = "Text", nullable)]
    pub file_path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub preview: Option<String>,
    pub size: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub metadata: Option<String>,
    pub source_app: Option<String>,
    pub created_at: DateTimeUtc,
    pub last_accessed_at: Option<DateTimeUtc>,
    pub access_count: i32,
    pub is_favorite: i32,
    pub sync_status: String,
    pub sync_version: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
