//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "local_files")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub path: String,
    pub r#type: i32,
    pub created_at: i64,
    pub access_count: i32,
    pub is_valid: i32,
    pub size: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub source_clipboard_id: Option<String>,
    pub source_type: i32,
    pub is_favorite: i32,
    pub share_mode: i32,
    pub expires_at: Option<i64>,
    pub updated_at: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
