//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "shared_files")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub path: String,
    pub r#type: i32,
    pub created_at: i64,
    pub access_count: i32,
    pub size: Option<i64>,
    pub cache_status: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub remote_name: Option<String>,
    pub remote_type: i32,
    pub remote_size: Option<i64>,
    pub remote_updated_at: Option<i64>,
    pub last_accessed_at: Option<i64>,
    pub sync_policy: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
